In [2]:
# !pip install Faker
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.0-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp314-cp314-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 39.6 MB/s  0:00:00eta 0:00:01
Downloading numpy-2.4.0-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 38.3 MB/s  0:00:00
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
Successfully installed numpy-2.4.0 pandas-2.3.3 pytz-2025.2

In [87]:
import datetime
from datetime import timedelta
from random import sample

random.seed(42)
start_date = datetime.date(2026,6,11)
end_date = start_date+timedelta(days=90)

start = start_date
random_90_dates = [start_date]

while start_date != end_date:
    start_date += timedelta(days=1)
    random_90_dates.append(start_date)

# random K dates from pack
random_50_dates = sample(random_90_dates, k=50)
random_50_dates.sort()
match_dates = random_50_dates

In [91]:
import pandas as pd
import random
import datetime
##table1
# match id
# home team_id
# away team_id
# stadium id
# match date

team_rows = []
stadium_rows = []
match_rows = []
team_ids = ["T01","T02","T03","T04","T05","T06","T07","T08","T09","T10"]
team_name = ["France","Senegal","South Africa","Spain","Switzerland","Argentina","Uruguay","England",
"Croatia", "Belgium"]

for i in range(len(team_ids)):
    team_row = {
        "team_id": team_ids[i],
        "team_name": team_name[i]
        }
    team_rows.append(team_row)
    
team_table = pd.DataFrame.from_records(team_rows)
# print(team_table)

###table2
stadium_ids = ["S01","S02","S03","S04","S05","S06","S07","S08","S09","S10"]
stadium_names = ["Lumen Field","BC Place","MetLife Stadium",
"Mercedes-Benz Stadium","BMO Field","AT&T Stadium","NRG Stadium","GEHA Field at Arrowhead Stadium",
"SoFi Stadium","Hard Rock Stadium","Levi’s Stadium","Lincoln Financial Field"]
stadium_capacity = [random.randint(50,70)*1000 for i in range(10)]
avg_ticket_price = [random.randint(500,1000) for i in range(10)]

for i in range(len(stadium_ids)):
    stadium_row = {
        "stadium_id": stadium_ids[i],
        "stadium_name": stadium_names[i],
        "stadium_capacity": stadium_capacity[i],
        "avg_ticket_price": avg_ticket_price[i]
    }
    stadium_rows.append(stadium_row)

stadium_table = pd.DataFrame.from_records(stadium_rows)
# print(stadium_table)

match_ids = [str(i) for i in range(1,51)]
match_ids = list(map(lambda x: "M"+ x, match_ids))

for i in range(len(match_ids)):
    home = random.choice(team_ids)
    away = random.choice([t for t in team_ids if t != home])

    match_row = {
        "match_id": match_ids[i],
        "home_team_id": home,
        "away_team_id": away,
        "stadium_id": random.choice(stadium_ids),
        "match_date": match_dates[i]
    }
    match_rows.append(match_row)
match_table = pd.DataFrame.from_records(match_rows)
# print(match_table)

In [94]:
stadium_table.head()

  stadium_id           stadium_name  stadium_capacity  avg_ticket_price
0        S01            Lumen Field             61000               591
1        S02               BC Place             67000               877
2        S03        MetLife Stadium             63000               973
3        S04  Mercedes-Benz Stadium             69000               670
4        S05              BMO Field             54000               900

In [109]:
random.choice([x for x in range(1,10)])

4

In [112]:
total_transactions_num = 100
x=[]
for i in range(total_transactions_num):
    user_id  = "FIFAW26"+str(i).zfill(6)
    x.append(user_id)
print(x)

['FIFAW26000000', 'FIFAW26000001', 'FIFAW26000002', 'FIFAW26000003', 'FIFAW26000004', 'FIFAW26000005', 'FIFAW26000006', 'FIFAW26000007', 'FIFAW26000008', 'FIFAW26000009', 'FIFAW26000010', 'FIFAW26000011', 'FIFAW26000012', 'FIFAW26000013', 'FIFAW26000014', 'FIFAW26000015', 'FIFAW26000016', 'FIFAW26000017', 'FIFAW26000018', 'FIFAW26000019', 'FIFAW26000020', 'FIFAW26000021', 'FIFAW26000022', 'FIFAW26000023', 'FIFAW26000024', 'FIFAW26000025', 'FIFAW26000026', 'FIFAW26000027', 'FIFAW26000028', 'FIFAW26000029', 'FIFAW26000030', 'FIFAW26000031', 'FIFAW26000032', 'FIFAW26000033', 'FIFAW26000034', 'FIFAW26000035', 'FIFAW26000036', 'FIFAW26000037', 'FIFAW26000038', 'FIFAW26000039', 'FIFAW26000040', 'FIFAW26000041', 'FIFAW26000042', 'FIFAW26000043', 'FIFAW26000044', 'FIFAW26000045', 'FIFAW26000046', 'FIFAW26000047', 'FIFAW26000048', 'FIFAW26000049', 'FIFAW26000050', 'FIFAW26000051', 'FIFAW26000052', 'FIFAW26000053', 'FIFAW26000054', 'FIFAW26000055', 'FIFAW26000056', 'FIFAW26000057', 'FIFAW26000058', 'FIFAW26000059', 'FIFAW26000060', 'FIFAW26000061', 'FIFAW26000062', 'FIFAW26000063', 'FIFAW26000064', 'FIFAW26000065', 'FIFAW26000066', 'FIFAW26000067', 'FIFAW26000068', 'FIFAW26000069', 'FIFAW26000070', 'FIFAW26000071', 'FIFAW26000072', 'FIFAW26000073', 'FIFAW26000074', 'FIFAW26000075', 'FIFAW26000076', 'FIFAW26000077', 'FIFAW26000078', 'FIFAW26000079', 'FIFAW26000080', 'FIFAW26000081', 'FIFAW26000082', 'FIFAW26000083', 'FIFAW26000084', 'FIFAW26000085', 'FIFAW26000086', 'FIFAW26000087', 'FIFAW26000088', 'FIFAW26000089', 'FIFAW26000090', 'FIFAW26000091', 'FIFAW26000092', 'FIFAW26000093', 'FIFAW26000094', 'FIFAW26000095', 'FIFAW26000096', 'FIFAW26000097', 'FIFAW26000098', 'FIFAW26000099']

In [169]:
purchase_time[0]

datetime.date(2026, 5, 24)

datetime.datetime(2026, 6, 11, 0, 0)

In [182]:
from datetime import datetime

def get_purchase_time(match_date):
    purchase_time = datetime.combine(
        match_date,
        datetime.min.time()
    ) - timedelta(
            days=random.randint(1, 60),
            hours=random.randint(0, 23),
            minutes=random.randint(0, 59),
            seconds = random.randint(0,59)
        )
    return purchase_time

In [ ]:
###Transactional_data
## Purchase time and date
### amount

## match id
## user_id
### user_name (faker)
### user_email (faker)
## Quantity
### Ticket_ID
quantity_choices = [x for x in range(1,10)]
transactions = []
import uuid
from faker import Faker
Faker.seed(42)
fake = Faker()
total_transactions_num = 50000
ticket_categories_map = {'GA':1,'Student':0.7,'VIP':1.3}


for i in range(total_transactions_num):
    match_id = random.choice(match_ids)
    stadium_id = match_table[match_table["match_id"]==match_id]['stadium_id'].iloc[0]
    stadium_name = stadium_table[stadium_table["stadium_id"]==stadium_id]['stadium_name'].iloc[0]
    quantity = random.choice(quantity_choices)
    ticket_category = random.choice(list(ticket_categories_map.keys()))
    ticket_multiplier = ticket_categories_map[ticket_category]
    amount = stadium_table[stadium_table["stadium_id"]==stadium_id]['avg_ticket_price'].iloc[0]*quantity*ticket_multiplier
    match_date = match_table[match_table["match_id"]==match_id]['match_date'].iloc[0]
    purchase_time = get_purchase_time(match_date)

    
    ticketId = str(uuid.uuid4())
    
    user_id  = "FIFAW26"+str(i).zfill(6)
    user_name = fake.first_name() + " " + fake.last_name()
    user_email = fake.unique.ascii_free_email()
    
    transactions.append({
        "ticket_id": ticketId,
        "match_id": match_id,
        "user_id": user_id,
        "user_name": user_name,
        "user_email": user_email,
        "ticket_type": ticket_category,
        "quantity": quantity,
        "stadium": stadium_name,
        "price": round(amount, 2),
        "purchase_timestamp": purchase_time
    })

base_df = pd.DataFrame(transactions)
base_df.head()

,ticket_id,match_id,user_id,user_name,user_email,ticket_type,quantity,stadium,price,purchase_timestamp
0,f3603aff-ac80-4341-bc27-be7342825626,M38,FIFAW26000000,Danielle Johnson,john21@hotmail.com,GA,6,BC Place,5262.0,2026-06-29 19:18:09
1,a7e4a99f-5033-4ec9-a229-3df7550deb87,M22,FIFAW26000001,Joy Gardner,fjohnson@gmail.com,GA,7,MetLife Stadium,6811.0,2026-05-20 03:57:19
2,fe06d027-4a25-48d3-879f-4c2f72bb7f7e,M19,FIFAW26000002,Jesse Guzman,jennifermiles@yahoo.com,GA,6,BC Place,5262.0,2026-06-01 16:42:28
3,cfad8f39-98ba-4517-8867-c33c59ed1cd6,M18,FIFAW26000003,Jeffrey Lawrence,blakeerik@yahoo.com,Student,2,BC Place,1227.8,2026-05-12 21:40:41
4,3682996b-2805-4a75-b81d-d3ba28e0d857,M11,FIFAW26000004,Matthew Moore,curtis61@yahoo.com,Student,2,Lumen Field,827.4,2026-06-01 13:18:10

In [185]:
base_df.to_csv('transaction_data.csv')

In [187]:
def generate_ingest_time(purchase_time):
    r = random.random()
    if r < 0.01:
        return purchase_time + timedelta(days=random.randint(1, 3))  # very late
    elif r < 0.11:
        return purchase_time + timedelta(hours=random.randint(1, 12))  # late
    else:
        return purchase_time + timedelta(minutes=random.randint(1, 30))  # normal

In [188]:
base_df["ingest_timestamp"] = base_df["purchase_timestamp"].apply(generate_ingest_time)
base_df.head()

,ticket_id,match_id,user_id,user_name,user_email,ticket_type,quantity,stadium,price,purchase_timestamp,ingest_timestamp
0,f3603aff-ac80-4341-bc27-be7342825626,M38,FIFAW26000000,Danielle Johnson,john21@hotmail.com,GA,6,BC Place,5262.0,2026-06-29 19:18:09,2026-06-29 20:18:09
1,a7e4a99f-5033-4ec9-a229-3df7550deb87,M22,FIFAW26000001,Joy Gardner,fjohnson@gmail.com,GA,7,MetLife Stadium,6811.0,2026-05-20 03:57:19,2026-05-20 04:02:19
2,fe06d027-4a25-48d3-879f-4c2f72bb7f7e,M19,FIFAW26000002,Jesse Guzman,jennifermiles@yahoo.com,GA,6,BC Place,5262.0,2026-06-01 16:42:28,2026-06-01 16:46:28
3,cfad8f39-98ba-4517-8867-c33c59ed1cd6,M18,FIFAW26000003,Jeffrey Lawrence,blakeerik@yahoo.com,Student,2,BC Place,1227.8,2026-05-12 21:40:41,2026-05-12 21:52:41
4,3682996b-2805-4a75-b81d-d3ba28e0d857,M11,FIFAW26000004,Matthew Moore,curtis61@yahoo.com,Student,2,Lumen Field,827.4,2026-06-01 13:18:10,2026-06-01 17:18:10

In [196]:
num_duplicates = int(0.05 * len(base_df))
dup_rows = base_df.sample(num_duplicates)

duplicates = []

for _, row in dup_rows.iterrows():
    for _ in range(random.randint(1, 2)):
        dup = row.copy()
        dup["ingest_timestamp"] += timedelta(minutes=random.randint(5, 60))
        duplicates.append(dup)

dup_df = pd.DataFrame(duplicates)

In [197]:
messy_transactions = pd.concat([base_df, dup_df], ignore_index=True)
messy_transactions = messy_transactions.sample(frac=1).reset_index(drop=True)
messy_transactions.to_csv(
    "ticket_purchases_raw.csv",
    index=False
)